### ISSUE TITLE
version.py missing bug

### ISSUE THREAD

**Issue by pitylee** [cvarelaruiz/owi2plex#16]
Hi,

I have found a bug, when trying to run from /usr/local/bin/owi2plex it will say version.py is missing (which I am not sure if is really missing when installing via pip3).

So I have cloned the repo, installed the requirements, and when I try to run the command it fails saying version.py is missing, which, in fact, it may be not, althrough since it looks for the file in the directory you are currently in, it is.

This may be, because the version.py file reading is not an absolute path, idk.

**My workaround was:**
Editing  /usr/local/bin/owi2plex
And changing the whole file to this:

`
#!/usr/bin/env bash

cd /usr/local/lib/python3.6/dist-packages/owi2plex/

python3 ./owi2plex.py "$@"
`

This may not be nice, but it works, it passes all the arguments from the global executable to wherever you have it installed, and it executes.

Hope someone can use this temporarily, while it will be fixed.

**Comment by cvarelaruiz** [comment]
@pitylee thanks for reporting the bug - You're right the path was specified as relative so I've fixed it now so it'll always be asbolute now.

release v0.1-alpha8 fixes this

**Comment by wivaku** [comment]
I get the same issue:

```
owi2plex -h myhost -o ~/guide.xml
Traceback (most recent call last):
  File "/usr/local/bin/owi2plex", line 5, in <module>
    from owi2plex import main
  File "/usr/local/bin/owi2plex.py", line 14, in <module>
    exec(open(os.path.dirname(os.path.realpath(__file__))+'/version.py').read())
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/version.py'
```

Install details:
```
pip install owi2plex
Requirement already satisfied: owi2plex in /usr/local/lib/python3.7/site-packages (0.1a8)
Requirement already satisfied: click==7.0 in /usr/local/lib/python3.7/site-packages (from owi2plex) (7.0)
Requirement already satisfied: pyyaml==5.1.2 in /usr/local/lib/python3.7/site-packages (from owi2plex) (5.1.2)
Requirement already satisfied: lxml==4.3.2 in /usr/local/lib/python3.7/site-packages (from owi2plex) (4.3.2)
Requirement already satisfied: future==0.17.1 in /usr/local/lib/python3.7/site-packages (from owi2plex) (0.17.1)
Requirement already satisfied: requests==2.21.0 in /usr/local/lib/python3.7/site-packages (from owi2plex) (2.21.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests==2.21.0->owi2plex) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests==2.21.0->owi2plex) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests==2.21.0->owi2plex) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests==2.21.0->owi2plex) (1.24.3)
```

Package details:
```
pip show -f owi2plex
Name: OWi2Plex
Version: 0.1a8
Summary: Exporter of EPG from OpenWebif to XMLTV to use with Plex
Home-page: https://github.com/cvarelaruiz/owi2plex
Author: Cristian Varela
Author-email: cvarelaruiz@gmail.com
License: MPL-2.0
Location: /usr/local/lib/python3.7/site-packages
Requires: click, pyyaml, future, requests, lxml
Required-by:
Files:
  ../../../bin/__pycache__/owi2plex.cpython-37.pyc
  ../../../bin/owi2plex
  ../../../bin/owi2plex.py
  OWi2Plex-0.1a8.dist-info/INSTALLER
  OWi2Plex-0.1a8.dist-info/LICENSE
  OWi2Plex-0.1a8.dist-info/METADATA
  OWi2Plex-0.1a8.dist-info/RECORD
  OWi2Plex-0.1a8.dist-info/WHEEL
  OWi2Plex-0.1a8.dist-info/entry_points.txt
  OWi2Plex-0.1a8.dist-info/top_level.txt
```

**Comment by steef84** [comment]
Same error here.. No fix yet

EDIT: for me sudo pip3 install owi2plex==0.1a5 got me a working version

**Comment by cvarelaruiz** [comment]
@wivaku, @steef84 you are right. The build process wasn't copying the file. I've fixed that now and created a new release.

You can download from here or install via pip.

Enjoy.

**Comment by steef84** [comment]
Still same error for v 0.1a9 

```
Traceback (most recent call last):
  File "/usr/local/bin/owi2plex", line 6, in <module>
    from owi2plex import main
  File "/usr/local/bin/owi2plex.py", line 14, in <module>
    exec(open(os.path.dirname(os.path.realpath(__file__))+'/version.py').read())
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/version.py'
```

**Comment by cvarelaruiz** [comment]
Yes indeed install version 0.1a9b

**Comment by wivaku** [comment]
Is 0.1a9b a release that can be installed using pip? It seems to keep using v0.1a8.
```
╰─ pip install owi2plex --no-cache-dir
Collecting owi2plex
  Downloading OWi2Plex-0.1a8-py2.py3-none-any.whl (13 kB)
```

**Comment by wivaku** [comment]
@cvarelaruiz: would you have news about how to get 0.1a9b using pip?

**Comment by cvarelaruiz** [comment]
@wivaku just created a new relase (0.1a10) that can be installed from pip.

Try `pip install owi2plex `

or `pip install owi2plex==0.1a10`

**Comment by wivaku** [comment]
Thanks, this one works!
