### ISSUE TITLE
BUG Help!!

### ISSUE THREAD

**Issue by jeromim** [cvarelaruiz/owi2plex#18]
208/5000
If I live in Brazil, I have accentuation in certain letters and the program is creating characters in place of letters, eg "ç, é, ã" is there any way to fix this? thank you

    <desc lang="en">Jordan e Bear disputam a aten&#231;&#227;o de uma das participantes.
    <title lang="en">De F&#233;rias com o Ex 3&#170; Temp. Ep. 3</title>
     <desc lang="en">Sabe tudo de M&#250;sica? Conhece todas as peculiaridades dos video clipes do seu artista Favorito? Ent&#227;o vem mostrar que voc&#234; conhece tudo de M&#250;sica no nosso Quiz MTV Guru Master</desc>

**Comment by cvarelaruiz** [comment]
@jeromim, the reason is because the text is converted to XML which is meant to be HTML friendly (those are the equivalent HTML codes of those characters). I'll have a look and see if I can de-HTML the descriptions and titles.

**Comment by jeromim** [comment]
thanks :* +1:

**Comment by cvarelaruiz** [comment]
@jeromim I just made a release that fixes that issue. Hope this works for you. 
Look for 0.1a11 available in the release section, install it via pip or clone this repo
