### ISSUE TITLE
Channel names and Picons

### ISSUE THREAD

**Issue by p3yot3p** [cvarelaruiz/owi2plex#19]
Is there a way to get the channel names exported and possibly also picons too so the browsing makes more sense in Plex? Right now everything is named channel 1 and channel 2 etc.
And without picons you have to guess what the channel is from the program in the EPG.

**Comment by cvarelaruiz** [comment]
Hey @p3yot3p, not sure exactly wha tyou mean. I can see picons in the guide as well as channels name. 
![Guide Details](https://user-images.githubusercontent.com/11735412/83942437-3feef700-a7eb-11ea-99d4-a8fbc4b92310.png)
![Programme Details](https://user-images.githubusercontent.com/11735412/83942439-41202400-a7eb-11ea-87d2-f0fe8e478984.png)

Can you perhaps attach a fragment of the channel section in the generated EPG file? Mine looks like this:

```
  <channel id="2101">
    <display-name>RTÉ One</display-name>
    <display-name>1</display-name>
    <icon src="http://192.168.0.150:80/picon/rteone.png"/>
  </channel>
  <channel id="2111">
    <display-name>RTÉ One +1</display-name>
    <display-name>2</display-name>
    <icon src="http://192.168.0.150:80/picon/rteoneplus1.png"/>
  </channel>
  <channel id="1102">
    <display-name>RTÉ2</display-name>
    <display-name>3</display-name>
    <icon src="http://192.168.0.150:80/picon/rte2.png"/>
  </channel>
  <channel id="1103">
    <display-name>Virgin Media 1</display-name>

```

**Comment by cvarelaruiz** [comment]
Clossing issue - Picons requires the Enigma box to have them installed so the API can provide them as above.

See example guide for OpenVix https://www.world-of-satellite.com/showthread.php?53119-Picons-How-to-add-picons-to-your-receiver&s=63877dec2b0fa57d62d6d74d16669c5c
