### ISSUE TITLE
help epg!

### ISSUE THREAD

**Issue by jeromim** [cvarelaruiz/owi2plex#20]
![image](https://user-images.githubusercontent.com/16826745/86719924-e8ff5c00-bffa-11ea-80cc-b74a29571541.png)
----------------------------------------------------------------------------------------------------------------------------------------

I live in Brazil, when I create the EPG instead of the words come with an accent, for example (amanhã, coração) the words are in characters, for example (amanh**#233**, cora**&#227**ao) Is there any way to fix this problem?

 thank you.

**Comment by cvarelaruiz** [comment]
Hey @jeromim, what version are you using? I pushed a patch last month (v0.1-alpha11) to allow for UTF characters. See an example of my EPG's output:

```
<channel id="2101">
    <display-name>RTÉ One</display-name>
    <display-name>1</display-name>
...
<programme channel="2101" start="20200607120000 +0100" stop="20200607130000 +0100">
    <length units="minutes">60</length>
    <desc lang="en">Discussion and analysis of the latest political issues with Ministers, TDs and Senators, along with in-depth reports from RTÉ's political staff.</desc>
```

You can see accents, both in the description and the channel name.

**Comment by cvarelaruiz** [comment]
Closing this issue as this was addressed in version 01-alpha11.
