### ISSUE TITLE
pip install owi2plex not working

### ISSUE THREAD

**Issue by dfgsaerh** [cvarelaruiz/owi2plex#22]
Hi
This project looks super interesting and want to try it out but any machine I run 'pip install owi2plex' on its giving the same error
I've installed the latest version of Python 3.8 
It bombs out at 
` Building lxml version 4.3.2.
    Building without Cython.
    ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
    ** make sure the development packages of libxml2 and libxslt are installed **`

Any help would be greatly appreciated

**Comment by cvarelaruiz** [comment]
Hi @dfgsaerh, this package uses an external library called lxml (https://lxml.de/) to generate the XML file with the EPG.

If you look at the requirements for that package (https://lxml.de/installation.html) it says that you need to install:

`sudo apt-get install libxml2-dev libxslt-dev python-dev`
- libxml2 version 2.9.2 or later.
- libxslt version 1.1.27 or later.

Depending on your distribution the command might vary, but in a debian based installation you can get those by installing with apt-get:

`sudo apt-get install libxml2-dev libxslt-dev python-dev`
