### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jeromim** [cvarelaruiz/owi2plex#7]
I tried python 2 and python 3 ubuntu and it did not work.

root@Desktop:/mnt/f/owi2plex-master# python owi2plex.py -b Variedades -h 192.168.1.108 -P 1080 -u root -p dreambox -o /tmp/epg.xml
Getting EPG for Service 1.Arte 1 (130) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:82:34:1:B54AF58:0:0:0:
Getting EPG for Service 2.BIS (144) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:90:4:1:B54B020:0:0:0:
Getting EPG for Service 3.Comedy Central (92) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:5C:32:1:B543124:0:0:0:
Getting EPG for Service 4.Curta! (159) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:9F:32:1:B543124:0:0:0:
Getting EPG for Service 5.E! (54) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:36:32:1:B543124:0:0:0:
Getting EPG for Service 6.Fish TV (52) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:34:2:1:B54314C:0:0:0:
Getting EPG for Service 7.Food Network (35) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:23:1:1:B542FBC:0:0:0:
Getting EPG for Service 8.GNT (41) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:29:2:1:B54314C:0:0:0:
Getting EPG for Service 9.Lifetime (79) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:4F:4:1:B54B020:0:0:0:
Getting EPG for Service 10.Mais Globosat (131) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:83:4:1:B54B020:0:0:0:
Getting EPG for Service 11.NHK (156) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:9C:2:1:B54314C:0:0:0:
Getting EPG for Service 12.Play TV (118) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:76:33:1:B543174:0:0:0:
Getting EPG for Service 13.Polishop TV (176) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:B0:2:1:B54314C:0:0:0:
Getting EPG for Service 14.TruTV (88) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:58:1:1:B542FBC:0:0:0:
Getting EPG for Service 15.TLC (124) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:7C:36:1:B5430D4:0:0:0:
Getting EPG for Service 16.SIC Internacional (150) from http://root:dreambox@192.168.1.108:1080/api/epgservice?sRef=1:0:1:96:33:1:B543174:0:0:0:
Traceback (most recent call last):
  File "owi2plex.py", line 381, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "owi2plex.py", line 369, in main
    tzoffset = getOffset(api_root_url=api_root_url)
  File "owi2plex.py", line 128, in getOffset
    now = datetime.timestamp(datetime.now())
AttributeError: type object 'datetime.datetime' has no attribute 'timestamp'
root@Desktop:/mnt/f/owi2plex-master#

**Comment by awsmfab** [comment]
See https://github.com/cvarelaruiz/owi2plex/issues/6#issuecomment-493752695

**Comment by cvarelaruiz** [comment]
As @awsmfab suggest, this is due to incompatibility with Python2. Try Python3 as seen in issue #6.

Leaving open as code will either:

* Have to cater for Python2.X
* Remove completely support for Py2.

**Comment by cvarelaruiz** [comment]
OWI2Plex won't work on Python2 without major rework and therefore it'll only work with Python3. 
Sorry
