### ISSUE TITLE
No continuous channel numbering

### ISSUE THREAD

**Issue by MrNick4B** [cvarelaruiz/owi2plex#8]
There is no option to use continuous channel numbering.
When using multiple bouquets, the channels from every bouquet get numbered from 1 to X.

All channels appear in the XML, but Plex does not recognize that channels with the same numbers are seperate channels.
Instead, Plex uses the last channel from the XML with that number.

I think the numbering happens in `def addChannels2XML`, specifically at the following line:
`etree.SubElement(channel, 'display-name').text = str(service['pos'])`

Maybe it could be useful to add an option to use incremental numbers, something like:
```python
def addChannels2XML(xmltv, bouquets_services, epg, api_root_url):
    number = 1
        for _, services in bouquets_services.items():
            for service in services:
                ...
                etree.SubElement(channel, 'display-name').text = str(number)
                number += 1
                ...
```

**Comment by cvarelaruiz** [comment]
@MrNick4B thanks for the pull request. I've merged it into Master and will put them into Pypi today.
